### ISSUE TITLE
Prepare release on pypi

### ISSUE THREAD

**Issue by tschm** [cvxgrp/spcqe#2]
@giray98 @bmeyers What's your intention with this code? Do you want to publish this as a professional package on pypi?

**Comment by tschm** [comment]
Have a look here https://github.com/cvxgrp/cvxbson or https://github.com/cvxgrp/simulator

**Comment by bmeyers** [comment]
Hey @tschm,

Yeah, we'll be using GitHub actions for CI/CD and deployment to PyPI and Conda. We'll generally follow the pattern in https://github.com/cvxgrp/qss and https://github.com/cvxgrp/signal-decomposition.

Cheers,
Bennet

**Comment by tschm** [comment]
That's great. I wouldn't invest the effort to deploy to Conda though. It's a lot of extra hassle for almost nothing...

**Comment by bmeyers** [comment]
Thanks for sharing your perspective, but we'll continue to follow the deployment procedure we've been developing over the years. I myself happen to make use of conda.
