### ISSUE TITLE
PyPI not updated with most recent release

### ISSUE THREAD

**Issue by bmeyers** [cvxgrp/spcqe#9]
The Python Package Index is still showing `v0.0.1a0` when the current released version is `v0.0.2`.

https://pypi.org/project/spcqe/

**Comment by bmeyers** [comment]
workflow failed here, I didn't catch it at the time (3 months ago): https://github.com/cvxgrp/spcqe/actions/runs/10014751354

**Comment by pluflou** [comment]
Repository was missing the PyPI credentials. I added them as environment secrets to the "deployment" environment. This should fix this. If it fails at next deployment we can reassess, but closing this for now.
